### ISSUE TITLE
Return value of Edalzell\Forma\ConfigController::preProcess() must be of the type array, null returned 

### ISSUE THREAD

**Issue by sandersjj** [edalzell/statamic-forma#3]
Hey Erin,

First of all thanks for this plugin. 
In the `serviceprovider` of my plugin I added 

```
$this->app->booted(function(){
            Forma::add('myaddon/test');
});
```
I also created a `config.yaml`:
```
api_key:
  display: 'Api Key'
  type: text
  read_only: true
```

But when I go to the setting page in my Control panel I get:

```
Return value of Edalzell\Forma\ConfigController::preProcess() must be of the type array, null returned 
```

In the manual it says that the second parameter in the add method is optional.

**Comment by edalzell** [comment]
Do you have a `test.php` config file in `config/`?

**Comment by sandersjj** [comment]
No, I don't have a `test.php` in `config/`.

**Comment by edalzell** [comment]
You’ll need a config file, and then publish it.

**Comment by sandersjj** [comment]
Can you elaborate on it? 
I don't see it in the readme. I also checked https://github.com/silentzco/statamic-mailchimp, but I didn't see how to do it.

**Comment by edalzell** [comment]
If you're going to have a config file, you need to actually have one in your package, see here: https://github.com/silentzco/statamic-mailchimp/tree/main/config.

This is not really a Forma thing...this is a Laravel thing. https://laravel.com/docs/8.x/packages#configuration

So if your addon is called `Test` you need a `config/test.php` in your addon. Then folks can publish it, then update it via Forma.
