### ISSUE TITLE
Compatibility with laravel 9

### ISSUE THREAD

**Issue by artisanbarista** [edalzell/statamic-forma#6]
Please add laravel 9 support.

Not working with latest  statamic v3.3.2 and laravel v9.5.1.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires edalzell/forma ^1.0 -> satisfiable by edalzell/forma
[v1.0].
    - edalzell/forma v1.0 requires laravel/framework ^7.30.3 || ^8.24 -> found laravel
/framework[v7.30.3, ..., 7.x-dev, v8.24.0, ..., 8.x-dev] but it conflicts with your ro
ot composer.json require (^9.0).

**Comment by simonhamp** [comment]
@leonchris perhaps you could raise a PR widening the version constraint range of `laravel/framework` in `composer.json`?

Probably just needs a `|| ^9.0` added to the existing constraints.

(I'd do it, but don't have access to a laptop this week)

This might make it easier for @edalzell to test, approve and release sooner.

**Comment by edalzell** [comment]
done in 1.1
